site_name: HealthAnalytics Docs
site_description: Documentação do Sistema de Predição de Obesidade
site_author: Pedro Alves
repo_url: https://github.com/hpedroh/obesity

theme:
  name: material
  language: pt
  features:
    - navigation.tabs
    - content.code.copy
  palette:
    # 1. Configuração automática para quem usa MODO CLARO no sistema
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Alternar para modo escuro

    # 2. Configuração automática para quem usa MODO ESCURO no sistema
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Alternar para modo claro

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Início: index.md
  - Documentação da Modelagem: modeling.md
  - Guia de Instalação: installation.md
  - Guia do Usuário: user_guide.md
  - Detalhes Técnicos: technical.md